### ISSUE TITLE
官方版本在哪里？

### ISSUE THREAD

**Issue by dengyh1994** [yihui/MSG#29]
在[博主简历](https://yihui.name/cn/vitae/)界面并没有找到这本《现代统计图形》，请问官方版本从哪里下载呀？

**Comment by yihui** [comment]
https://yihui.name/cn/2018/09/index-zero/

**Comment by yixuan** [comment]
如果你晚一天回复，我应该就会回相同的内容。:joy:

**Comment by yihui** [comment]
看来还是我用 Github 太频繁了。

**Comment by dengyh1994** [comment]
谢谢两位大佬的答复！
